version: "3.9"
services:
  jupyter:
    container_name: jupyter
    image: auto-watermark-detection3
    build:
      context: .
      dockerfile: Dockerfile3
    environment:
      GRANT_SUDO: "yes"
    volumes:
      - type: bind
        source: .
        target: /home/jovyan
    ports:
      - "8888:8888"
